config/routes.rb
PropShop::Application.routes.draw do

  get "pages/index"
  root "pages#index"

  get "api" => "pages#api"
  get "contact" => "pages#contact"
  get "deploy" => "pages#deploy"

  get "about" => "pages#about"
  get "pages/about" => "pages#about"
  get "pages/find" => "pages#find"
  post "pages/search" => "pages#search"
  get "pages/search" => "pages#search"
  get "pages/contact" => "pages#contact"
  post "pages/email" => "pages#email"
  get "pages/api" => "pages#api"
  get "pages/browse/:category" => "pages#browse"

  resources :model
  resources :user

  get 'model/:id/image/:num' => 'model#image'
  get 'model/:id/sdf' => 'model#sdf'
  get 'model/:id/edit' => 'model#edit'
  get 'model/:id/rate' => 'model#rate'
  get 'model/:id/download' => 'model#download'
  get 'model/:id/like/:user' => 'model#like'
  get 'model/exists/:name' => 'model#exists'
  post 'model/:id/modify' => 'model#modify'

  get 'user' => 'user#index'
  get 'user/:id/downloads' => 'user#downloads'
  get 'user/:id/created' => 'user#created'
  get 'user/:id/likes' => 'user#likes'

  resource :session, only: [:new, :create, :destroy]

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>The Prop Shop</title>
  <script src="http://code.jquery.com/jquery.js"></script> 
  <%= favicon_link_tag 'propshop.ico' %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Google Analytics -->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-27596536-3', 'thepropshop.org');
    ga('send', 'pageview');
  </script>

</head>
<body>

<div style="min-height: 100%; width: 100%; height: auto !important; margin: 0 0 -70px 0; padding: 0;">

<div class="navbar navbar-static-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" style="margin-top:20px" data-toggle="collapse"
        data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <span class="nav">
      <%= link_to image_tag("propshop_logo.svg",
                            alt:"OSRF logo", :class=>"brand"), root_path%>
      </span>

      <div class="nav-collapse">
        <ul class="nav navbar-nav nav-pills">
          <% if @post[:controller] == "pages" and @post[:action] == "find" %>
            <li class='active'>
          <% else %>
            <li>
          <% end %>
            <%= link_to "Find", pages_find_path%></li>

          <% if @post[:controller] == "model" and @post[:action] == "new" %>
            <li class='active'>
          <% else %>
            <li>
          <% end %>
            <%= link_to "Upload", controller: "model", action: "new"%></li>

          <% if @post[:controller] == "pages" and @post[:action] == "about" %>
            <li class='active'>
          <% else %>
            <li>
          <% end %>
          <%= link_to "About", controller: "pages", action: "about"%></li>

        </ul>


        <span class="nav" style="padding-top:0px">
          <%= form_tag("/pages/search",
                       :class => "nav-search", :method=>"get") do%>
  
            <%= text_field_tag(:search, "",
                         :class=>"input-xlarge nav-search-input",
                         :placeholder=>"Search",
                         :value => "#{@post[:search]}",
                         :required=>true) %>
          <%end%>
        </span>

        <ul class="nav pull-right" style="margin-top: 10px">
          <li class="dropdown">
            <%if !signed_in?%>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Login | Sign up
              </a>
              <ul class='dropdown-menu' style="text-align: left">
                <li>
                  <%= link_to "#{image_tag('google-icon-32.png', alt:"google")} Google".html_safe, {:controller=>"sessions", :action=>"new", :auth=>"google", :redirect=>"#{request.original_url}"}%>
                </li>

                <li>
                  <%= link_to "#{image_tag('yahoo-icon-32.png', alt:"yahoo")} Yahoo".html_safe, {:controller=>"sessions", :action=>"new", :auth=>"yahoo", :redirect=>"#{request.original_url}"}%>
                </li>

                <li>
                  <%= link_to "#{image_tag('openid-icon-32.png', alt:"openid")} OpenID".html_safe, {:controller=>"sessions", :action=>"new", :auth=>"openid", :redirect=>"#{request.original_url}"}%>
                </li>

                <li>
                  <%= link_to "#{image_tag('aol-icon-32.png')} AOL".html_safe,
                      {:controller=>"sessions", :action=>"new", :auth=>"aol",
                        :redirect=>"#{request.original_url}"}%>
                </li>
              </ul>
            <%else%>
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <span id="current_username">
                  <%= current_user.username%>
                </span>&nbsp;
              </a>
              <ul class="dropdown-menu" style="text-align: left">
                <li>
                  <%= link_to 'Models I Like <i class="icon-heart"></i>'.html_safe, {:controller=>"user", :action=>"likes", :id=>current_user.id}%>
                </li>
                <li>
                  <%= link_to "My Downloads", 
                        {:controller=>"user", :action=>"downloads",
                          :id=>current_user.id} %>
                </li>
                <li>
                  <%= link_to "Models I Made", 
                        {:controller=>"user", :action=>"created",
                          :id=>current_user.id} %>
                </li>
                <li>
                  <%= link_to "Log out",
                        {:controller=>"sessions", :action=>"destroy"},
                        :method=>:delete%>
                </li>
              </ul>
            <%end%>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
   <%if @post[:controller] == "pages" and @post[:action] == "index" %>
    <div class="hero-unit" style="margin-top:-1px; border-radius:0px">
      <div class="container" style="padding:40px">
	
  
        <div style="background-color: rgba(64,72,83,0.8);width: 420px;padding:12px;border-radius: 4px; color: #ffffff ">
          <h3 style="font-family:Helvetica; font-size:150%;">Welcome to The Prop Shop</h3>
          <p>ThePropShop is a diverse and open source marketplace for 3D models.  Download models for free and use them in simulation environments like <a href="http://gazebosim.org" target="_blank" style="color: orange">Gazebo</a>. Upload your own work so everyone can join in the fun. </p>
        </div>
      </div>
    </div>
  <%end%>

  <div class="container">
    <% if @post[:controller] != "pages" ||
      (@post[:controller] == "pages" and @post[:action] != "index") %>
      <%= breadcrumbs %>
    <%end%>
    
    <div style="margin-bottom:75px">

      <%= yield %>
    </div>
  </div>
</div>

<footer id="footer">
  <section class="footer-body">
  <ul style="text-align:center">
    <li><%= link_to "Contact", contact_path() %></li>
    <li><%= link_to "API", api_path()%></li>
    <li><%= link_to "Deploy", controller: "pages", action: "deploy"%></li>
  </ul>
  <%= link_to image_tag("byosrf.svg", alt: "by osrf"), "http://osrfoundation.org", :style=>"" %>
  </section>
</footer>


<!--This is the modal for signing up-->
<div id="signup_modal" class="modal hide fade" tabindex="-1" role="dialog"
  aria-labelledby="signup_modal" aria-hidden="true">

  <div class="modal-header">
    <h3 id="myModalLabel">Pick a username</h3>
    <p>Select a username to associate with your OpenID account.</p>
  </div>

  <div class="modal-body">
    <%= form_for :user, remote:true,
      :url => {:controller=>:user, :action => :create},
      :html => {:id=>"username_form"} do |f| %>

        <%if current_user%>
          <input type="hidden" name="id" value="<%=current_user.id%>"/>
        <%end%>

        <div class="control-group" id="username_div">
          <label>Username*</label>
          <div class="controls">
            <%= f.text_field "username", {:placeholder=>"Pick a username...",
              :required=>true}%>
            <span class="help-inline" id="username_help"
              style="padding-bottom:10px"></span>
          </div>
        </div>

        <div class="control-group" id="confirm_div">
          <label>Re-type username*</label>
          <div class="controls">
            <%= f.text_field "confirm", {:placeholder=>"Type if again...",
              :required=>true}%>
            <span class="help-inline" id="confirm_help"
              style="padding-bottom:10px"></span>
          </div>
        </div>

      <div class="signup-buttons pull-left">
        <button class="btn btn-default" name="button" onclick="deleteUser();" >Cancel</button>
      </div>

      <div class="signup-buttons pull-right">
        <%= f.submit "Submit", :class => "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

<script>
  function validateUsernameForm()
  {
    var username = document.forms["username_form"]["user[username]"].value;
    var username2 = document.forms["username_form"]["user[confirm]"].value;
    document.getElementById('username_help').innerHTML = "";
    document.getElementById('confirm_help').innerHTML = "";

    document.getElementById('username_div').className = "control-group";
    document.getElementById('confirm_div').className = "control-group";

    if (username != null && username != "" && username == username2)
    {
      return true;
    }
    else
    {
      if (username == null || username == "")
      {
        document.getElementById('username_div').className += " error";
        document.getElementById('username_help').innerHTML =
        "Please choose a username";
      }
      else if (username != username2)
      {
        document.getElementById('confirm_div').className += " error";
        document.getElementById('confirm_help').innerHTML =
        "Username must match";
      }
      return false;
    }
  }

  function deleteUser()
  {
    <%if signed_in? %>
    $.ajax({
      url: <%= "\"/user/#{current_user.id.to_s}\"".html_safe %>,
      type: "DELETE",
      async: false,
      success: function() {
      }
    });
    $("#signup_modal").modal("hide");
    location.reload();
  <%end%>

  }

  function logout()
  {
    $.ajax({
      url: "/session",
      method: "DELETE",
      async: false,
      success: function() {
        document.location = "/";
      }
    });
  }

  <%if current_user && !current_user.username%>
    /* Don't all the user to exit the modal using ESC or clicking away */
    $('#signup_modal').modal({
      backdrop: 'static',
      keyboard: false
    });
  <%end%>

  $('#username_form').submit(function() {
    if (validateUsernameForm())
    {
      var valuesToSubmit = $(this).serialize();

      $.ajax({
        url: $(this).attr('action'),
        data: valuesToSubmit,
        type: 'POST',
        dataType: 'JSON',
        success: function(_json) {

          if (_json["status"] == "success")
          {
            document.getElementById("current_username").innerHTML =
            _json["message"];
            $('#signup_modal').modal('hide');
          }
          else 
          {
            document.getElementById('username_help').innerHTML =
            _json["message"];
          }
        }
      });
    }
    return false;
  });

</script>
</body>
</html>